# Copyright (C) 2025 Advanced Micro Devices, Inc. All rights reserved.
# Portions of this file consist of AI-generated content.

"""Generate ``runtime/values.local.yaml`` (the helm overlay).

Hand-written YAML emitter — no PyYAML / ruamel.yaml dependency. The output
is byte-for-byte identical to what the bash ``generate_values_overlay``
function emits, so the chart, the helm merge and the Hub Python config
(``runtime/hub/core/config.py``) all see exactly the same data structure.
"""

from __future__ import annotations

import re
from io import StringIO
from pathlib import Path

from auplc_installer.catalog import (
    BASE_TEAM_MAPPING,
    NONE_SENTINEL,
    CourseSelection,
    parse_selection_spec,
)
from auplc_installer.gpu import GpuConfig, is_curated_sku
from auplc_installer.util import InstallerError, log

# Resource name → image basename (used by acceleratorOverrides emission
# when SKUs straddle gfx families). Ordered list matches the bash version
# so YAML emission is deterministic.
_RESOURCE_IMAGE_BASE: dict[str, str] = {
    "gpu": "auplc-base",
    "code-gpu": "auplc-code-gpu",
    "Course-CV": "auplc-cv",
    "Course-DL": "auplc-dl",
    "Course-LLM": "auplc-llm",
    "Course-PhySim": "auplc-physim",
}


GPU_RESOURCE_KEYS: tuple[str, ...] = tuple(_RESOURCE_IMAGE_BASE.keys())


def emit_overlay(
    cfg: GpuConfig,
    *,
    image_registry: str,
    image_tag: str,
    courses: CourseSelection,
    offline_mode: bool,
) -> str:
    """Render the overlay as a string. Pure function — no I/O."""
    buf = StringIO()
    primary_tag = f"{image_tag}-{cfg.gpu_target}"
    homogeneous_target = cfg.homogeneous_target
    filter_courses = not courses.is_default()

    # --- header comments ---
    buf.write("# Auto-generated by auplc-installer.\n")
    buf.write(f"# Detected SKU keys : {' '.join(s.accel_key for s in cfg.skus)}\n")
    products = ", ".join(s.product_name or "<unknown>" for s in cfg.skus)
    buf.write(f"# Product names    : {products}\n")
    buf.write(f"# Primary gfx tag  : {cfg.gpu_target}\n")
    if not homogeneous_target:
        targets = " ".join(s.gpu_target for s in cfg.skus)
        buf.write(f"# Mixed gfx targets: {targets}\n")
    buf.write(f"# Env selection : {courses.description()}\n")
    buf.write("# Regenerated on install/upgrade.\n")
    buf.write("custom:\n")

    # --- accelerators ---
    any_accel_emitted = False
    for sku in cfg.skus:
        if is_curated_sku(sku.accel_key):
            # Only emit an override when there's a non-trivial reason:
            #   - product name was detected (pin nodeSelector to the real SKU)
            #   - HSA_OVERRIDE_GFX_VERSION applies (phx family)
            if not sku.product_name and not sku.accel_env:
                continue
            if not any_accel_emitted:
                buf.write("  accelerators:\n")
                any_accel_emitted = True
            buf.write(f"    {sku.accel_key}:\n")
            if sku.product_name:
                buf.write("      nodeSelector:\n")
                buf.write(f'        amd.com/gpu.product-name: "{sku.product_name}"\n')
            if sku.accel_env:
                buf.write("      env:\n")
                buf.write(f'        HSA_OVERRIDE_GFX_VERSION: "{sku.accel_env}"\n')
        else:
            if not any_accel_emitted:
                buf.write("  accelerators:\n")
                any_accel_emitted = True
            display_text = sku.display_name or (sku.product_name.replace("_", " ") if sku.product_name else "")
            if not display_text:
                display_text = f"AMD GPU ({sku.accel_key})"
            selector_product = sku.product_name or sku.accel_key
            buf.write(f"    # SKU '{sku.accel_key}' is not curated in values.yaml; stanza injected by installer.\n")
            buf.write("    # For production / multi-node deployments, copy this block into values.yaml.\n")
            buf.write(f"    {sku.accel_key}:\n")
            buf.write(f'      displayName: "{display_text}"\n')
            buf.write(f'      description: "Auto-detected ({sku.gpu_target})"\n')
            buf.write("      nodeSelector:\n")
            buf.write(f'        amd.com/gpu.product-name: "{selector_product}"\n')
            if sku.accel_env:
                buf.write("      env:\n")
                buf.write(f'        HSA_OVERRIDE_GFX_VERSION: "{sku.accel_env}"\n')
            else:
                buf.write("      env: {}\n")
            buf.write(f"      quotaRate: {sku.quota_rate}\n")

    # --- resources block: GPU course images + metadata ---
    emit_resources = [r for r in GPU_RESOURCE_KEYS if not filter_courses or courses.is_selected(r)]
    if emit_resources:
        buf.write("  resources:\n")
        buf.write("    images:\n")
        for resource in emit_resources:
            base_name = _RESOURCE_IMAGE_BASE[resource]
            buf.write(f'      {resource}: "{image_registry}/{base_name}:{primary_tag}"\n')
        buf.write("    metadata:\n")
        for resource in emit_resources:
            buf.write(f"      {resource}:\n")
            buf.write("        acceleratorKeys:\n")
            for sku in cfg.skus:
                buf.write(f"          - {sku.accel_key}\n")
            if not homogeneous_target:
                base_name = _RESOURCE_IMAGE_BASE[resource]
                wrote_overrides = False
                for sku in cfg.skus:
                    if sku.gpu_target != cfg.gpu_target:
                        if not wrote_overrides:
                            buf.write("        acceleratorOverrides:\n")
                            wrote_overrides = True
                        buf.write(f"          {sku.accel_key}:\n")
                        buf.write(f'            image: "{image_registry}/{base_name}:{image_tag}-{sku.gpu_target}"\n')

    # --- teams.mapping filter (only when course selection is in effect) ---
    if filter_courses:
        buf.write("  teams:\n")
        buf.write("    mapping:\n")
        # Iterate in the same order as the bash associative-array enumeration.
        # Bash on Linux walks the dict in arbitrary order, so we use the
        # insertion order of BASE_TEAM_MAPPING which is stable in Python 3.7+
        # and matches what humans expect when reading the file.
        for team, base_courses in BASE_TEAM_MAPPING.items():
            picks_set = set(courses.picks)
            out_courses = [c for c in base_courses if c in picks_set]
            if not out_courses:
                buf.write(f"      {team}: []\n")
            else:
                buf.write(f"      {team}:\n")
                for c in out_courses:
                    buf.write(f"        - {c}\n")

    # --- offline-bundle hub.image override ---
    if offline_mode:
        buf.write("hub:\n")
        buf.write("  image:\n")
        buf.write(f'    name: "{image_registry}/auplc-hub"\n')
        buf.write(f'    tag: "{image_tag}"\n')
        buf.write("    pullPolicy: IfNotPresent\n")

    return buf.getvalue()


def generate_values_overlay(
    cfg: GpuConfig,
    *,
    image_registry: str,
    image_tag: str,
    courses: CourseSelection,
    offline_mode: bool,
    overlay_path: Path,
) -> Path:
    """Render the overlay and write it to ``overlay_path``. Returns the path."""
    log(f"Generating values overlay: {overlay_path}")
    overlay_path.parent.mkdir(parents=True, exist_ok=True)
    text = emit_overlay(
        cfg,
        image_registry=image_registry,
        image_tag=image_tag,
        courses=courses,
        offline_mode=offline_mode,
    )
    overlay_path.write_text(text, encoding="utf-8")
    return overlay_path


# Inverse of ``CourseSelection.description()`` as embedded in the overlay
# header by :func:`emit_overlay`. Used by upgrade flows so that a bare
# ``rt upgrade`` (no ``--courses=`` flag) preserves whatever the user
# originally installed with instead of silently expanding to "all".
_COURSE_HEADER_RE = re.compile(r"^# (?:Env selection|Course selection)\s*:\s*(.+?)\s*$")


def try_load_courses_from_overlay(overlay_path: Path) -> CourseSelection | None:
    """Best-effort recovery of a previously installed course selection.

    Reads the ``# Course selection : …`` comment that
    :func:`emit_overlay` writes at the top of every overlay file and turns
    it back into a :class:`CourseSelection`. Returns ``None`` when the
    file is missing, the header line is absent, or the spec it carries
    can't be re-parsed (e.g. because someone hand-edited the comment).

    Callers should treat ``None`` as "I don't know what was there before"
    and fall back to whatever default they would have used otherwise.
    """
    if not overlay_path.is_file():
        return None
    try:
        text = overlay_path.read_text(encoding="utf-8")
    except OSError:
        return None
    for line in text.splitlines():
        m = _COURSE_HEADER_RE.match(line)
        if not m:
            continue
        spec = m.group(1)
        # The two sentinel descriptions don't round-trip through
        # parse_selection_spec because they contain non-key tokens
        # ("(default)") or are themselves keywords.
        if spec == "all (default)":
            return CourseSelection.default()
        if spec == "none":
            return CourseSelection(picks=[NONE_SENTINEL])
        try:
            return parse_selection_spec(spec)
        except InstallerError:
            return None
    return None


# Re-exported so callers can import ``NONE_SENTINEL`` from a single module
# without dipping into the lower-level catalog module.
__all__ = [
    "emit_overlay",
    "generate_values_overlay",
    "try_load_courses_from_overlay",
    "GPU_RESOURCE_KEYS",
    "NONE_SENTINEL",
]
