apiVersion: v1
kind: PersistentVolume
metadata:
  name: hami-lc-home-nfs
  labels:
    type: nfs
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.2
    - hard
    - timeo=600
  nfs:
    server: nas-server
    path: ${NAS_HOME_EXPORT}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hami-lc-home
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  volumeName: hami-lc-home-nfs
  storageClassName: ""

