#!/usr/bin/env bash
# Render local deployment artifacts from .env.local (gitignored).
#
#   ./scripts/render_local.sh
#
# Reads:  .env.local                      (repo root, gitignored; see .env.local.example)
# Writes: runtime/values.local.yaml       (helm overlay: hub node pinning; gitignored)
#         build/nfs-home.yaml             (rendered from deploy/hami/nfs-home.yaml)
#         build/nfs-user-home.yaml
#         build/nfs-rwx-test.yaml
#         build/amd-time-slice-test.yaml
#
# The committed manifests contain ${VAR} placeholders and are NOT valid as-is;
# always kubectl apply the rendered copies under build/.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

ENV_FILE=".env.local"
if [[ ! -f "$ENV_FILE" ]]; then
  echo "error: $ENV_FILE not found." >&2
  echo "       cp .env.local.example .env.local   # then fill in real values" >&2
  exit 1
fi

set -a
# shellcheck disable=SC1091
. "$ENV_FILE"
set +a

HUB_NODE_HOSTNAME="${HUB_NODE_HOSTNAME:-}"
NAS_SERVER="${NAS_SERVER:-}"
NAS_HOME_EXPORT="${NAS_HOME_EXPORT:-}"
AMD_GPU_NODE_HOSTNAME="${AMD_GPU_NODE_HOSTNAME:-}"

command -v envsubst >/dev/null 2>&1 || { echo "error: envsubst not found (apt-get install gettext-base)" >&2; exit 1; }

# --- helm overlay (hub node pinning) ----------------------------------------
if [[ -n "$HUB_NODE_HOSTNAME" ]]; then
  {
    echo "# GENERATED by scripts/render_local.sh from .env.local - do not edit."
    printf 'hub:\n  nodeSelector:\n    kubernetes.io/hostname: %s\n' "$HUB_NODE_HOSTNAME"
  } > runtime/values.local.yaml
  echo "wrote runtime/values.local.yaml (hub node: $HUB_NODE_HOSTNAME)"
else
  rm -f runtime/values.local.yaml
  echo "note: HUB_NODE_HOSTNAME empty; removed runtime/values.local.yaml (no node pinning)"
fi

# --- rendered manifests ------------------------------------------------------
rm -rf build
mkdir -p build

render() { # $1=source $2=dest $3=envsubst format string
  envsubst "$3" < "$1" > "build/$2"
  echo "wrote build/$2"
}

if [[ -n "$NAS_SERVER" && -n "$NAS_HOME_EXPORT" ]]; then
  render "deploy/hami/nfs-home.yaml" "nfs-home.yaml" '$NAS_SERVER $NAS_HOME_EXPORT'
  render "deploy/hami/nfs-user-home.yaml" "nfs-user-home.yaml" '$NAS_SERVER $NAS_HOME_EXPORT'
  render "deploy/hami/tests/nfs-rwx-test.yaml" "nfs-rwx-test.yaml" '$NAS_SERVER $NAS_HOME_EXPORT'
  grep -qE '^    server: \S' build/nfs-home.yaml || { echo "error: NAS_SERVER did not render into build/nfs-home.yaml" >&2; exit 1; }
else
  echo "warn: NAS_SERVER/NAS_HOME_EXPORT empty in $ENV_FILE; skipping NFS manifests" >&2
fi

if [[ -n "$AMD_GPU_NODE_HOSTNAME" ]]; then
  render "deploy/amd/tests/amd-time-slice-test.yaml" "amd-time-slice-test.yaml" '$AMD_GPU_NODE_HOSTNAME'
else
  echo "warn: AMD_GPU_NODE_HOSTNAME empty in $ENV_FILE; skipping amd-time-slice-test.yaml" >&2
fi

echo ""
echo "Next:"
echo "  helm:    ./scripts/helm_upgrade.bash          (picks up runtime/values.local.yaml)"
echo "  nfs:     kubectl apply -f build/nfs-home.yaml (plus other rendered files in build/)"
echo "  join.sh: set -a; . ./$ENV_FILE; set +a"
echo "           sudo -E ./join.sh --server \"\$K3S_SERVER_IP\" --token <K3S_TOKEN> [--vendor nvidia|amd]"
