# Copyright (C) 2025 Advanced Micro Devices, Inc. All rights reserved.
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""
JWT Token-based Authenticator

Legacy authenticator that uses JWT tokens generated by FPGARemoteLab.
"""

from __future__ import annotations

import datetime
import os
import re

import jwt
from jupyterhub.auth import Authenticator
from tornado import web


class RemoteLabAuthenticator(Authenticator):
    """
    Legacy JWT token-based authenticator.

    Uses tokens generated by FPGARemoteLab for authentication.
    """

    @staticmethod
    def _camelCaseify(s):
        """Convert snake_case to camelCase."""
        return re.sub(r"_([a-z])", lambda m: m.group(1).upper(), s)

    @staticmethod
    def _get_current_utc_timestamp():
        dt = datetime.datetime.now(datetime.timezone.utc)
        utc_time = dt.replace(tzinfo=datetime.timezone.utc)
        utc_timestamp = utc_time.timestamp()
        return int(utc_timestamp)

    @staticmethod
    def _decode_jwt(token, handler=None):
        with open(os.getenv("JWT_PUBLIC_KEY_FILE", "/usr/local/etc/jupyterhub/jwt_public_key.pem")) as f:
            JWT_PUBLIC_KEY = f.read()
        try:
            payload = jwt.decode(token, JWT_PUBLIC_KEY, algorithms="EdDSA")
        except jwt.ExpiredSignatureError:
            print("JWT Info: JWT Expired!")
            return None
        except jwt.InvalidSignatureError:
            print("JWT Info: Not signed by trusted server!")
            return None
        except jwt.DecodeError as e:
            print(f"JWT Info: {e}")
            return None
        except Exception as e:
            if handler:
                handler.log.warning(f"JWT Info: JWT Invalid! {e}")
            return None
        return payload["data"]

    custom_html = """
    <form action="{{ base_url }}login?next={{ next | urlencode }}"
                method="post"
                role="form">
            <div class="auth-form-header">
              <h1>Sign in</h1>
            </div>
            <div class='auth-form-body m-auto'>
              <input type="hidden" name="_xsrf" value="{{ xsrf }}" />
              <input type="hidden" id="username_input" name="username" value="Invalid" />
              <div id="auth-result" class="alert" style="display:none;margin-bottom:12px;"></div>
              <label for='password_input'>Password:</label>
              <input type="password"
                     class="form-control"
                     autocomplete="current-password"
                     name="password"
                     id="password_input" />
              <div class="feedback-container">
                <input id="login_submit"
                       type="submit"
                       class='btn btn-jupyter form-control'
                       value='Sign in'
                       tabindex="3" />
                <div class="feedback-widget hidden">
                  <i class="fa fa-spinner"></i>
                </div>
              </div>
              <script>
                document.querySelector('form').addEventListener('submit', function(e) {
                  const resultDiv = document.getElementById('auth-result');
                  resultDiv.style.display = 'none';
                });
              </script>
    """

    async def authenticate(self, handler, data=None):
        if data is None:
            raise web.HTTPError(400, "No authentication data provided")
        token = data["password"]
        jwt_data = self._decode_jwt(token, handler)

        error_msg = None
        if jwt_data is None:
            error_msg = "JWT token is invalid or expired"
            handler.log.warning(error_msg)
            raise web.HTTPError(401, error_msg)
        elif jwt_data["type"] != "jupyterhub-token":
            error_msg = f"Unknown token type: {jwt_data['type']}"
            handler.log.warning(error_msg)
            raise web.HTTPError(401, error_msg)

        handler.log.info("Authentication successful")
        return jwt_data["username"]
